library(tidyverse)
# signals: dataframe with significant SNPs. Assumes column names generated by rMVP. 
# trait: name (as a string) of the column identifyin which trait the SNP was significant for
# ld_file_prefix: string of prefix preceding chromosome number in ld file paths
# signal_file_path: path to signal file to include in output signal file list
# trait_list_prefix: string prefix before list number to save output traitlist files to
# file_list_prefix: string prefix to save file lists to
generatePeakCallingTextFiles <- function(signals, trait, ld_file_prefix, traits_per_list, signal_file_path, trait_list_prefix, file_list_prefix, min_snps_per_peak=3)
{
  peakCallingList <- signals %>% 
    rowwise() %>% 
    mutate(ld_file = str_c(ld_file_prefix, CHROM, '.csv')) %>% 
    ungroup() %>%
    group_by(ld_file, .data[[trait]]) %>%
    summarise(n_snps = n()) %>% 
    filter(n_snps >= min_snps_per_peak) %>%
    arrange(ld_file)
  
  f_num_total <- 1
  ld_file_list <- c()
  signal_file_list <- c()
  chrom_list <- c()
  for(f in unique(peakCallingList$ld_file))
  {
    cur_list <- filter(peakCallingList, ld_file==f)
    start <- 1
    n_traits <- nrow(cur_list)
    f_num_ld_file <- 1
    while(start < n_traits)
    {
      end <- start + traits_per_list
      if(end > n_traits)
      {
        end <- n_traits
      }
      write.table(cur_list[[trait]][start:end], str_c(trait_list_prefix, f_num_total, '.txt'), quote = FALSE, row.names = FALSE, col.names = FALSE)
      f_num_total <- f_num_total + 1
      ld_file_list <- c(ld_file_list, f)
      signal_file_list <- c(signal_file_list, signal_file_path)
      chrom_list <- c(chrom_list, CHROM)
      f_num_ld_file <- f_num_ld_file + 1
      start <- end + 1
    }
    print(f)
    print(f_num_ld_file)
  }
  
  write.table(ld_file_list, str_c(file_list_prefix, '_ldfile.txt'), quote = FALSE, row.names = FALSE, col.names = FALSE)
  write.table(signal_file_list, str_c(file_list_prefix, '_signalfile.txt'), quote = FALSE, row.names = FALSE, col.names = FALSE)
  write.table(str_c(trait_list_prefix, 1:(f_num_total-1), '.txt'), 
              str_c(file_list_prefix, '_traitlistfile.txt'), 
              quote = FALSE, row.names = FALSE, col.names = FALSE)
  write.table(chrom_list, str_c(file_list_prefix, '_chromfile.txt'), quote = FALSE, row.names = FALSE, col.names = FALSE)
  return(peakCallingList)
}
