library(tidyverse)
# path: directory containing files with signal output in csv files
# trait: name of trait to get support for
# assumes signal files are in format generated by rMVP
getSupport <- function(path, trait)
{
  files <- Sys.glob(paste0(path, trait, '*.csv'))
  
  if (length(files) >= 1)
  {
    signals <- tibble()
    # print(tbl_sum(signals))
    
    for (i in 1:length(files))
    {
      currFile <- files[i]
      currFile <- read.csv(currFile, header = FALSE, skip = 1, col.names = c('SNP', 'CHROM', 'POS', 'REF', 'ALT', 'MAF', 'EFFECT', 'SE', 'P')) %>%
        as_tibble() %>%
        rowwise() %>%
        mutate(CHROM = as.numeric(str_remove(CHROM, 'chr'))) %>%
        select(c(SNP:POS, EFFECT:P))
      # print(tbl_sum(currFile))
      signals <- bind_rows(signals, currFile)
      # print(tbl_sum(signals))
    }
    
    # print(length(unique(signals$SNP)))
    
    signals <- signals %>%
      group_by(SNP, CHROM, POS) %>%
      summarise(EFFECT = mean(EFFECT), SE = mean(SE), P = mean(P), {{trait}} := n()/100)
    # print(tbl_sum(signals))
    # write.csv(signals, file = paste0(path, 'Z', trait, 'signals.csv'), quote = FALSE, row.names = FALSE, col.names = TRUE)
    
    return(signals)
  }
  else 
  {
    print(paste0('File not found.', trait))
  }
}
