library(tidyverse)
# Returns dataframe with concatenated rows of all csv files matching path. follows Sys.glob() wildcard rules.
# assumes format generated by rMVP
summariseSignals <- function(path)
{
  files <- Sys.glob(path)
  signals <- tibble()
  for(f in files)
  {
    df <- read_csv(f,
                   col_types = 'ccnccnnnn', 
                   col_names = c('SNP', 'CHROM', 'POS', 'REF', 'ALT', 'MAF', 'Effect', 'SE', 'p-val'),
                   skip = 1) %>% 
      mutate(filename = f)
    signals <- bind_rows(signals, df)
  }
  return(signals)
}
